### ISSUE TITLE
call "eth_getBlockByHash" result null

### ISSUE THREAD

**Issue by zwxin2012** [second-state/oasis-ssvm-runtime#34]
Today I use postmain to access "eth getBlockByHas" and result null.

Block Hash：

Block Height：

PRC：https://rpc.oasiseth.org:8545

Request：
curl --location --request POST 'https://rpc.oasiseth.org:8545/' \
--header 'Content-Type: application/json' \
--data-raw '{
	"jsonrpc":"2.0",
	"method":"eth_getBlockByHash",
	"params":[
		"0x6a76599fe47429a908521b69cd1ef7047196f2c1b382e38184025b2515325545", 
		true
	],
	"id":1
}'

Respone : 
{"jsonrpc":"2.0","result":null,"id":1}

**Comment by hydai** [comment]
Hi @zwxin2012,
Could you also provide the Block Number of this missing block?

**Comment by zwxin2012** [comment]
> Hi @zwxin2012,
> Could you also provide the Block Number of this missing block?

3219326
